### ISSUE TITLE
Not finding latest pact-node

### ISSUE THREAD

**Issue by soundstep** [pact-foundation/karma-pact#2] opened 2017-08-14 09:55 UTC
Karma-pact seems to break since the last updates (not sure which one precisely).

Here is a package.json that breaks:

```JSON
  "devDependencies": {
    "@pact-foundation/pact-node": "4.12.0",
    "karma-pact": "0.0.7",
```

On a centos 7 linux machine I get: 

```
17:22:16 11 08 2017 17:22:16.429:ERROR [plugin]: Error during loading "/home/jenkins-slave/workspace/node_modules/karma-pact" plugin:
17:22:16   Cannot find module '@pact-foundation/pact-provider-verifier-linux-x64'
17:22:16 Warning: No provider for "framework:pact"! (Resolving: framework:pact) Use --force to continue.
17:22:16 
17:22:16 Aborted due to warnings.
```

Here is one that works:

```
  "devDependencies": {
    "@pact-foundation/pact-node": "4.8.1",
    "karma-pact": "0.0.7",
```

I noticed a file change in the @pact-foundation/pact-node lib: `dist/pact.web.js` to `dist/pact-web.js`, it could be related?

Note: The pact-node dependency is present as I'm using it for other tasks.

**Comment by soundstep** [comment] 2017-08-14 10:11
Update, the problem might be related directly to pact-node with the latest version of nodejs, I opened another issue there:
https://github.com/pact-foundation/pact-node/issues/42

**Comment by mefellows** [comment] 2017-08-14 11:29
Thanks @soundstep, let's get to the bottom of this!

**Comment by mboudreau** [comment] 2017-09-19 01:39
Closing this as it's been identified where the issue is and is not related to karma-pact.

**Closed as completed by mboudreau** 2017-09-19 01:39 UTC
